# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Khanrc"
description:        "Khanrc's blog"

# URL
url:                "http://khanrc.github.io"
baseurl:            "assets"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# markdown: kramdown

# kramdown:
#   input: GFM

markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks", "no_intra_emphasis", "footnotes"]

# Navigation
nav:
  - name:           "About"
    href:           "/about"
  - name:           "Tags"
    href:           "/tags"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
